name: BackupMe
author: Endermanbugzjfc
api: 4.0.0
version: 1.1.3
main: Endermanbugzjfc\BackupMe\BackupMe
src-namespace-prefix: Endermanbugzjfc\BackupMe
description: Implements the "Pterodactyl backup system" but can also backup your server without restarting the server and for mainly made those who don't use Pterodactyl to use

commands:
  backupme:
    description: Backup server
    permission: backupme.cmd.backup
    aliases: [backup, backup-me]

permissions:
  backupme:
    backupme.cmd.backup:
      description: Permission to start a backup with command
      default: op